/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: types.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "types.pb-c.h"
void   hdnode_type__init
                     (HDNodeType         *message)
{
  static HDNodeType init_value = HDNODE_TYPE__INIT;
  *message = init_value;
}
size_t hdnode_type__get_packed_size
                     (const HDNodeType *message)
{
  assert(message->base.descriptor == &hdnode_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hdnode_type__pack
                     (const HDNodeType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hdnode_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hdnode_type__pack_to_buffer
                     (const HDNodeType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hdnode_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HDNodeType *
       hdnode_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HDNodeType *)
     protobuf_c_message_unpack (&hdnode_type__descriptor,
                                allocator, len, data);
}
void   hdnode_type__free_unpacked
                     (HDNodeType *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &hdnode_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   hdnode_path_type__init
                     (HDNodePathType         *message)
{
  static HDNodePathType init_value = HDNODE_PATH_TYPE__INIT;
  *message = init_value;
}
size_t hdnode_path_type__get_packed_size
                     (const HDNodePathType *message)
{
  assert(message->base.descriptor == &hdnode_path_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t hdnode_path_type__pack
                     (const HDNodePathType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &hdnode_path_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t hdnode_path_type__pack_to_buffer
                     (const HDNodePathType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &hdnode_path_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HDNodePathType *
       hdnode_path_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HDNodePathType *)
     protobuf_c_message_unpack (&hdnode_path_type__descriptor,
                                allocator, len, data);
}
void   hdnode_path_type__free_unpacked
                     (HDNodePathType *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &hdnode_path_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   coin_type__init
                     (CoinType         *message)
{
  static CoinType init_value = COIN_TYPE__INIT;
  *message = init_value;
}
size_t coin_type__get_packed_size
                     (const CoinType *message)
{
  assert(message->base.descriptor == &coin_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t coin_type__pack
                     (const CoinType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &coin_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t coin_type__pack_to_buffer
                     (const CoinType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &coin_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CoinType *
       coin_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CoinType *)
     protobuf_c_message_unpack (&coin_type__descriptor,
                                allocator, len, data);
}
void   coin_type__free_unpacked
                     (CoinType *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &coin_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   multisig_redeem_script_type__init
                     (MultisigRedeemScriptType         *message)
{
  static MultisigRedeemScriptType init_value = MULTISIG_REDEEM_SCRIPT_TYPE__INIT;
  *message = init_value;
}
size_t multisig_redeem_script_type__get_packed_size
                     (const MultisigRedeemScriptType *message)
{
  assert(message->base.descriptor == &multisig_redeem_script_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t multisig_redeem_script_type__pack
                     (const MultisigRedeemScriptType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &multisig_redeem_script_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t multisig_redeem_script_type__pack_to_buffer
                     (const MultisigRedeemScriptType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &multisig_redeem_script_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MultisigRedeemScriptType *
       multisig_redeem_script_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MultisigRedeemScriptType *)
     protobuf_c_message_unpack (&multisig_redeem_script_type__descriptor,
                                allocator, len, data);
}
void   multisig_redeem_script_type__free_unpacked
                     (MultisigRedeemScriptType *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &multisig_redeem_script_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tx_input_type__init
                     (TxInputType         *message)
{
  static TxInputType init_value = TX_INPUT_TYPE__INIT;
  *message = init_value;
}
size_t tx_input_type__get_packed_size
                     (const TxInputType *message)
{
  assert(message->base.descriptor == &tx_input_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tx_input_type__pack
                     (const TxInputType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tx_input_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tx_input_type__pack_to_buffer
                     (const TxInputType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tx_input_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TxInputType *
       tx_input_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TxInputType *)
     protobuf_c_message_unpack (&tx_input_type__descriptor,
                                allocator, len, data);
}
void   tx_input_type__free_unpacked
                     (TxInputType *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tx_input_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tx_output_type__init
                     (TxOutputType         *message)
{
  static TxOutputType init_value = TX_OUTPUT_TYPE__INIT;
  *message = init_value;
}
size_t tx_output_type__get_packed_size
                     (const TxOutputType *message)
{
  assert(message->base.descriptor == &tx_output_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tx_output_type__pack
                     (const TxOutputType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tx_output_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tx_output_type__pack_to_buffer
                     (const TxOutputType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tx_output_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TxOutputType *
       tx_output_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TxOutputType *)
     protobuf_c_message_unpack (&tx_output_type__descriptor,
                                allocator, len, data);
}
void   tx_output_type__free_unpacked
                     (TxOutputType *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tx_output_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tx_output_bin_type__init
                     (TxOutputBinType         *message)
{
  static TxOutputBinType init_value = TX_OUTPUT_BIN_TYPE__INIT;
  *message = init_value;
}
size_t tx_output_bin_type__get_packed_size
                     (const TxOutputBinType *message)
{
  assert(message->base.descriptor == &tx_output_bin_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tx_output_bin_type__pack
                     (const TxOutputBinType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tx_output_bin_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tx_output_bin_type__pack_to_buffer
                     (const TxOutputBinType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tx_output_bin_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TxOutputBinType *
       tx_output_bin_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TxOutputBinType *)
     protobuf_c_message_unpack (&tx_output_bin_type__descriptor,
                                allocator, len, data);
}
void   tx_output_bin_type__free_unpacked
                     (TxOutputBinType *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tx_output_bin_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   transaction_type__init
                     (TransactionType         *message)
{
  static TransactionType init_value = TRANSACTION_TYPE__INIT;
  *message = init_value;
}
size_t transaction_type__get_packed_size
                     (const TransactionType *message)
{
  assert(message->base.descriptor == &transaction_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transaction_type__pack
                     (const TransactionType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &transaction_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transaction_type__pack_to_buffer
                     (const TransactionType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &transaction_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TransactionType *
       transaction_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TransactionType *)
     protobuf_c_message_unpack (&transaction_type__descriptor,
                                allocator, len, data);
}
void   transaction_type__free_unpacked
                     (TransactionType *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &transaction_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tx_request_details_type__init
                     (TxRequestDetailsType         *message)
{
  static TxRequestDetailsType init_value = TX_REQUEST_DETAILS_TYPE__INIT;
  *message = init_value;
}
size_t tx_request_details_type__get_packed_size
                     (const TxRequestDetailsType *message)
{
  assert(message->base.descriptor == &tx_request_details_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tx_request_details_type__pack
                     (const TxRequestDetailsType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tx_request_details_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tx_request_details_type__pack_to_buffer
                     (const TxRequestDetailsType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tx_request_details_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TxRequestDetailsType *
       tx_request_details_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TxRequestDetailsType *)
     protobuf_c_message_unpack (&tx_request_details_type__descriptor,
                                allocator, len, data);
}
void   tx_request_details_type__free_unpacked
                     (TxRequestDetailsType *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tx_request_details_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tx_request_serialized_type__init
                     (TxRequestSerializedType         *message)
{
  static TxRequestSerializedType init_value = TX_REQUEST_SERIALIZED_TYPE__INIT;
  *message = init_value;
}
size_t tx_request_serialized_type__get_packed_size
                     (const TxRequestSerializedType *message)
{
  assert(message->base.descriptor == &tx_request_serialized_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tx_request_serialized_type__pack
                     (const TxRequestSerializedType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tx_request_serialized_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tx_request_serialized_type__pack_to_buffer
                     (const TxRequestSerializedType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tx_request_serialized_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TxRequestSerializedType *
       tx_request_serialized_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TxRequestSerializedType *)
     protobuf_c_message_unpack (&tx_request_serialized_type__descriptor,
                                allocator, len, data);
}
void   tx_request_serialized_type__free_unpacked
                     (TxRequestSerializedType *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &tx_request_serialized_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   identity_type__init
                     (IdentityType         *message)
{
  static IdentityType init_value = IDENTITY_TYPE__INIT;
  *message = init_value;
}
size_t identity_type__get_packed_size
                     (const IdentityType *message)
{
  assert(message->base.descriptor == &identity_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t identity_type__pack
                     (const IdentityType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &identity_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t identity_type__pack_to_buffer
                     (const IdentityType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &identity_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IdentityType *
       identity_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IdentityType *)
     protobuf_c_message_unpack (&identity_type__descriptor,
                                allocator, len, data);
}
void   identity_type__free_unpacked
                     (IdentityType *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &identity_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xmr_output_type__init
                     (XmrOutputType         *message)
{
  static XmrOutputType init_value = XMR_OUTPUT_TYPE__INIT;
  *message = init_value;
}
size_t xmr_output_type__get_packed_size
                     (const XmrOutputType *message)
{
  assert(message->base.descriptor == &xmr_output_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xmr_output_type__pack
                     (const XmrOutputType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xmr_output_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xmr_output_type__pack_to_buffer
                     (const XmrOutputType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xmr_output_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
XmrOutputType *
       xmr_output_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (XmrOutputType *)
     protobuf_c_message_unpack (&xmr_output_type__descriptor,
                                allocator, len, data);
}
void   xmr_output_type__free_unpacked
                     (XmrOutputType *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &xmr_output_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xmr_input_type__init
                     (XmrInputType         *message)
{
  static XmrInputType init_value = XMR_INPUT_TYPE__INIT;
  *message = init_value;
}
size_t xmr_input_type__get_packed_size
                     (const XmrInputType *message)
{
  assert(message->base.descriptor == &xmr_input_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xmr_input_type__pack
                     (const XmrInputType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xmr_input_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xmr_input_type__pack_to_buffer
                     (const XmrInputType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xmr_input_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
XmrInputType *
       xmr_input_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (XmrInputType *)
     protobuf_c_message_unpack (&xmr_input_type__descriptor,
                                allocator, len, data);
}
void   xmr_input_type__free_unpacked
                     (XmrInputType *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &xmr_input_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   xmr_signature_type__init
                     (XmrSignatureType         *message)
{
  static XmrSignatureType init_value = XMR_SIGNATURE_TYPE__INIT;
  *message = init_value;
}
size_t xmr_signature_type__get_packed_size
                     (const XmrSignatureType *message)
{
  assert(message->base.descriptor == &xmr_signature_type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t xmr_signature_type__pack
                     (const XmrSignatureType *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &xmr_signature_type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t xmr_signature_type__pack_to_buffer
                     (const XmrSignatureType *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &xmr_signature_type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
XmrSignatureType *
       xmr_signature_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (XmrSignatureType *)
     protobuf_c_message_unpack (&xmr_signature_type__descriptor,
                                allocator, len, data);
}
void   xmr_signature_type__free_unpacked
                     (XmrSignatureType *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &xmr_signature_type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor hdnode_type__field_descriptors[6] =
{
  {
    "depth",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(HDNodeType, depth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fingerprint",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(HDNodeType, fingerprint),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "child_num",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(HDNodeType, child_num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chain_code",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(HDNodeType, chain_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "private_key",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(HDNodeType, has_private_key),
    offsetof(HDNodeType, private_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "public_key",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(HDNodeType, has_public_key),
    offsetof(HDNodeType, public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hdnode_type__field_indices_by_name[] = {
  3,   /* field[3] = chain_code */
  2,   /* field[2] = child_num */
  0,   /* field[0] = depth */
  1,   /* field[1] = fingerprint */
  4,   /* field[4] = private_key */
  5,   /* field[5] = public_key */
};
static const ProtobufCIntRange hdnode_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor hdnode_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "HDNodeType",
  "HDNodeType",
  "HDNodeType",
  "",
  sizeof(HDNodeType),
  6,
  hdnode_type__field_descriptors,
  hdnode_type__field_indices_by_name,
  1,  hdnode_type__number_ranges,
  (ProtobufCMessageInit) hdnode_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor hdnode_path_type__field_descriptors[2] =
{
  {
    "node",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(HDNodePathType, node),
    &hdnode_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address_n",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(HDNodePathType, n_address_n),
    offsetof(HDNodePathType, address_n),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned hdnode_path_type__field_indices_by_name[] = {
  1,   /* field[1] = address_n */
  0,   /* field[0] = node */
};
static const ProtobufCIntRange hdnode_path_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor hdnode_path_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "HDNodePathType",
  "HDNodePathType",
  "HDNodePathType",
  "",
  sizeof(HDNodePathType),
  2,
  hdnode_path_type__field_descriptors,
  hdnode_path_type__field_indices_by_name,
  1,  hdnode_path_type__number_ranges,
  (ProtobufCMessageInit) hdnode_path_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t coin_type__address_type__default_value = 0u;
static const uint32_t coin_type__address_type_p2sh__default_value = 5u;
static const uint32_t coin_type__address_type_p2wpkh__default_value = 6u;
static const uint32_t coin_type__address_type_p2wsh__default_value = 10u;
static const ProtobufCFieldDescriptor coin_type__field_descriptors[8] =
{
  {
    "coin_name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CoinType, coin_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "coin_shortcut",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CoinType, coin_shortcut),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address_type",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CoinType, has_address_type),
    offsetof(CoinType, address_type),
    NULL,
    &coin_type__address_type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxfee_kb",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(CoinType, has_maxfee_kb),
    offsetof(CoinType, maxfee_kb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address_type_p2sh",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CoinType, has_address_type_p2sh),
    offsetof(CoinType, address_type_p2sh),
    NULL,
    &coin_type__address_type_p2sh__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address_type_p2wpkh",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CoinType, has_address_type_p2wpkh),
    offsetof(CoinType, address_type_p2wpkh),
    NULL,
    &coin_type__address_type_p2wpkh__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address_type_p2wsh",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(CoinType, has_address_type_p2wsh),
    offsetof(CoinType, address_type_p2wsh),
    NULL,
    &coin_type__address_type_p2wsh__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signed_message_header",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CoinType, signed_message_header),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned coin_type__field_indices_by_name[] = {
  2,   /* field[2] = address_type */
  4,   /* field[4] = address_type_p2sh */
  5,   /* field[5] = address_type_p2wpkh */
  6,   /* field[6] = address_type_p2wsh */
  0,   /* field[0] = coin_name */
  1,   /* field[1] = coin_shortcut */
  3,   /* field[3] = maxfee_kb */
  7,   /* field[7] = signed_message_header */
};
static const ProtobufCIntRange coin_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor coin_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CoinType",
  "CoinType",
  "CoinType",
  "",
  sizeof(CoinType),
  8,
  coin_type__field_descriptors,
  coin_type__field_indices_by_name,
  1,  coin_type__number_ranges,
  (ProtobufCMessageInit) coin_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor multisig_redeem_script_type__field_descriptors[3] =
{
  {
    "pubkeys",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(MultisigRedeemScriptType, n_pubkeys),
    offsetof(MultisigRedeemScriptType, pubkeys),
    &hdnode_path_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signatures",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(MultisigRedeemScriptType, n_signatures),
    offsetof(MultisigRedeemScriptType, signatures),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "m",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(MultisigRedeemScriptType, has_m),
    offsetof(MultisigRedeemScriptType, m),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned multisig_redeem_script_type__field_indices_by_name[] = {
  2,   /* field[2] = m */
  0,   /* field[0] = pubkeys */
  1,   /* field[1] = signatures */
};
static const ProtobufCIntRange multisig_redeem_script_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor multisig_redeem_script_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MultisigRedeemScriptType",
  "MultisigRedeemScriptType",
  "MultisigRedeemScriptType",
  "",
  sizeof(MultisigRedeemScriptType),
  3,
  multisig_redeem_script_type__field_descriptors,
  multisig_redeem_script_type__field_indices_by_name,
  1,  multisig_redeem_script_type__number_ranges,
  (ProtobufCMessageInit) multisig_redeem_script_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t tx_input_type__sequence__default_value = 4294967295u;
static const InputScriptType tx_input_type__script_type__default_value = INPUT_SCRIPT_TYPE__SPENDADDRESS;
static const ProtobufCFieldDescriptor tx_input_type__field_descriptors[7] =
{
  {
    "address_n",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TxInputType, n_address_n),
    offsetof(TxInputType, address_n),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prev_hash",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TxInputType, prev_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prev_index",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(TxInputType, prev_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "script_sig",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(TxInputType, has_script_sig),
    offsetof(TxInputType, script_sig),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TxInputType, has_sequence),
    offsetof(TxInputType, sequence),
    NULL,
    &tx_input_type__sequence__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "script_type",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(TxInputType, has_script_type),
    offsetof(TxInputType, script_type),
    &input_script_type__descriptor,
    &tx_input_type__script_type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "multisig",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TxInputType, multisig),
    &multisig_redeem_script_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tx_input_type__field_indices_by_name[] = {
  0,   /* field[0] = address_n */
  6,   /* field[6] = multisig */
  1,   /* field[1] = prev_hash */
  2,   /* field[2] = prev_index */
  3,   /* field[3] = script_sig */
  5,   /* field[5] = script_type */
  4,   /* field[4] = sequence */
};
static const ProtobufCIntRange tx_input_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor tx_input_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TxInputType",
  "TxInputType",
  "TxInputType",
  "",
  sizeof(TxInputType),
  7,
  tx_input_type__field_descriptors,
  tx_input_type__field_indices_by_name,
  1,  tx_input_type__number_ranges,
  (ProtobufCMessageInit) tx_input_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tx_output_type__field_descriptors[6] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(TxOutputType, address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address_n",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TxOutputType, n_address_n),
    offsetof(TxOutputType, address_n),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "amount",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(TxOutputType, amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "script_type",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(TxOutputType, script_type),
    &output_script_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "multisig",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(TxOutputType, multisig),
    &multisig_redeem_script_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "op_return_data",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(TxOutputType, has_op_return_data),
    offsetof(TxOutputType, op_return_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tx_output_type__field_indices_by_name[] = {
  0,   /* field[0] = address */
  1,   /* field[1] = address_n */
  2,   /* field[2] = amount */
  4,   /* field[4] = multisig */
  5,   /* field[5] = op_return_data */
  3,   /* field[3] = script_type */
};
static const ProtobufCIntRange tx_output_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor tx_output_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TxOutputType",
  "TxOutputType",
  "TxOutputType",
  "",
  sizeof(TxOutputType),
  6,
  tx_output_type__field_descriptors,
  tx_output_type__field_indices_by_name,
  1,  tx_output_type__number_ranges,
  (ProtobufCMessageInit) tx_output_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tx_output_bin_type__field_descriptors[2] =
{
  {
    "amount",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(TxOutputBinType, amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "script_pubkey",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TxOutputBinType, script_pubkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tx_output_bin_type__field_indices_by_name[] = {
  0,   /* field[0] = amount */
  1,   /* field[1] = script_pubkey */
};
static const ProtobufCIntRange tx_output_bin_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tx_output_bin_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TxOutputBinType",
  "TxOutputBinType",
  "TxOutputBinType",
  "",
  sizeof(TxOutputBinType),
  2,
  tx_output_bin_type__field_descriptors,
  tx_output_bin_type__field_indices_by_name,
  1,  tx_output_bin_type__number_ranges,
  (ProtobufCMessageInit) tx_output_bin_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor transaction_type__field_descriptors[7] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TransactionType, has_version),
    offsetof(TransactionType, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputs",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TransactionType, n_inputs),
    offsetof(TransactionType, inputs),
    &tx_input_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bin_outputs",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TransactionType, n_bin_outputs),
    offsetof(TransactionType, bin_outputs),
    &tx_output_bin_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lock_time",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TransactionType, has_lock_time),
    offsetof(TransactionType, lock_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outputs",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TransactionType, n_outputs),
    offsetof(TransactionType, outputs),
    &tx_output_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inputs_cnt",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TransactionType, has_inputs_cnt),
    offsetof(TransactionType, inputs_cnt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "outputs_cnt",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TransactionType, has_outputs_cnt),
    offsetof(TransactionType, outputs_cnt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transaction_type__field_indices_by_name[] = {
  2,   /* field[2] = bin_outputs */
  1,   /* field[1] = inputs */
  5,   /* field[5] = inputs_cnt */
  3,   /* field[3] = lock_time */
  4,   /* field[4] = outputs */
  6,   /* field[6] = outputs_cnt */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange transaction_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor transaction_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TransactionType",
  "TransactionType",
  "TransactionType",
  "",
  sizeof(TransactionType),
  7,
  transaction_type__field_descriptors,
  transaction_type__field_indices_by_name,
  1,  transaction_type__number_ranges,
  (ProtobufCMessageInit) transaction_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tx_request_details_type__field_descriptors[2] =
{
  {
    "request_index",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TxRequestDetailsType, has_request_index),
    offsetof(TxRequestDetailsType, request_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tx_hash",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(TxRequestDetailsType, has_tx_hash),
    offsetof(TxRequestDetailsType, tx_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tx_request_details_type__field_indices_by_name[] = {
  0,   /* field[0] = request_index */
  1,   /* field[1] = tx_hash */
};
static const ProtobufCIntRange tx_request_details_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tx_request_details_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TxRequestDetailsType",
  "TxRequestDetailsType",
  "TxRequestDetailsType",
  "",
  sizeof(TxRequestDetailsType),
  2,
  tx_request_details_type__field_descriptors,
  tx_request_details_type__field_indices_by_name,
  1,  tx_request_details_type__number_ranges,
  (ProtobufCMessageInit) tx_request_details_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tx_request_serialized_type__field_descriptors[3] =
{
  {
    "signature_index",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(TxRequestSerializedType, has_signature_index),
    offsetof(TxRequestSerializedType, signature_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "signature",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(TxRequestSerializedType, has_signature),
    offsetof(TxRequestSerializedType, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serialized_tx",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(TxRequestSerializedType, has_serialized_tx),
    offsetof(TxRequestSerializedType, serialized_tx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tx_request_serialized_type__field_indices_by_name[] = {
  2,   /* field[2] = serialized_tx */
  1,   /* field[1] = signature */
  0,   /* field[0] = signature_index */
};
static const ProtobufCIntRange tx_request_serialized_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor tx_request_serialized_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TxRequestSerializedType",
  "TxRequestSerializedType",
  "TxRequestSerializedType",
  "",
  sizeof(TxRequestSerializedType),
  3,
  tx_request_serialized_type__field_descriptors,
  tx_request_serialized_type__field_indices_by_name,
  1,  tx_request_serialized_type__number_ranges,
  (ProtobufCMessageInit) tx_request_serialized_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t identity_type__index__default_value = 0u;
static const ProtobufCFieldDescriptor identity_type__field_descriptors[6] =
{
  {
    "proto",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IdentityType, proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IdentityType, user),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IdentityType, host),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IdentityType, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(IdentityType, path),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(IdentityType, has_index),
    offsetof(IdentityType, index),
    NULL,
    &identity_type__index__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned identity_type__field_indices_by_name[] = {
  2,   /* field[2] = host */
  5,   /* field[5] = index */
  4,   /* field[4] = path */
  3,   /* field[3] = port */
  0,   /* field[0] = proto */
  1,   /* field[1] = user */
};
static const ProtobufCIntRange identity_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor identity_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "IdentityType",
  "IdentityType",
  "IdentityType",
  "",
  sizeof(IdentityType),
  6,
  identity_type__field_descriptors,
  identity_type__field_indices_by_name,
  1,  identity_type__number_ranges,
  (ProtobufCMessageInit) identity_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor xmr_output_type__field_descriptors[2] =
{
  {
    "address_index",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(XmrOutputType, address_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "amount",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(XmrOutputType, amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xmr_output_type__field_indices_by_name[] = {
  0,   /* field[0] = address_index */
  1,   /* field[1] = amount */
};
static const ProtobufCIntRange xmr_output_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor xmr_output_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "XmrOutputType",
  "XmrOutputType",
  "XmrOutputType",
  "",
  sizeof(XmrOutputType),
  2,
  xmr_output_type__field_descriptors,
  xmr_output_type__field_indices_by_name,
  1,  xmr_output_type__number_ranges,
  (ProtobufCMessageInit) xmr_output_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor xmr_input_type__field_descriptors[5] =
{
  {
    "amount",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(XmrInputType, amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "derivation",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(XmrInputType, derivation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eph_pubkey",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(XmrInputType, eph_pubkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "out_tx_index",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(XmrInputType, out_tx_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offsets",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(XmrInputType, offsets),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xmr_input_type__field_indices_by_name[] = {
  0,   /* field[0] = amount */
  1,   /* field[1] = derivation */
  2,   /* field[2] = eph_pubkey */
  4,   /* field[4] = offsets */
  3,   /* field[3] = out_tx_index */
};
static const ProtobufCIntRange xmr_input_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor xmr_input_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "XmrInputType",
  "XmrInputType",
  "XmrInputType",
  "",
  sizeof(XmrInputType),
  5,
  xmr_input_type__field_descriptors,
  xmr_input_type__field_indices_by_name,
  1,  xmr_input_type__number_ranges,
  (ProtobufCMessageInit) xmr_input_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor xmr_signature_type__field_descriptors[4] =
{
  {
    "derivation",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(XmrSignatureType, derivation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pubkey",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(XmrSignatureType, pubkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(XmrSignatureType, has_stream),
    offsetof(XmrSignatureType, stream),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sum",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(XmrSignatureType, sum),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned xmr_signature_type__field_indices_by_name[] = {
  0,   /* field[0] = derivation */
  1,   /* field[1] = pubkey */
  2,   /* field[2] = stream */
  3,   /* field[3] = sum */
};
static const ProtobufCIntRange xmr_signature_type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor xmr_signature_type__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "XmrSignatureType",
  "XmrSignatureType",
  "XmrSignatureType",
  "",
  sizeof(XmrSignatureType),
  4,
  xmr_signature_type__field_descriptors,
  xmr_signature_type__field_indices_by_name,
  1,  xmr_signature_type__number_ranges,
  (ProtobufCMessageInit) xmr_signature_type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue failure_type__enum_values_by_number[12] =
{
  { "Failure_UnexpectedMessage", "FAILURE_TYPE__Failure_UnexpectedMessage", 1 },
  { "Failure_ButtonExpected", "FAILURE_TYPE__Failure_ButtonExpected", 2 },
  { "Failure_SyntaxError", "FAILURE_TYPE__Failure_SyntaxError", 3 },
  { "Failure_ActionCancelled", "FAILURE_TYPE__Failure_ActionCancelled", 4 },
  { "Failure_PinExpected", "FAILURE_TYPE__Failure_PinExpected", 5 },
  { "Failure_PinCancelled", "FAILURE_TYPE__Failure_PinCancelled", 6 },
  { "Failure_PinInvalid", "FAILURE_TYPE__Failure_PinInvalid", 7 },
  { "Failure_InvalidSignature", "FAILURE_TYPE__Failure_InvalidSignature", 8 },
  { "Failure_Other", "FAILURE_TYPE__Failure_Other", 9 },
  { "Failure_NotEnoughFunds", "FAILURE_TYPE__Failure_NotEnoughFunds", 10 },
  { "Failure_NotInitialized", "FAILURE_TYPE__Failure_NotInitialized", 11 },
  { "Failure_FirmwareError", "FAILURE_TYPE__Failure_FirmwareError", 99 },
};
static const ProtobufCIntRange failure_type__value_ranges[] = {
{1, 0},{99, 11},{0, 12}
};
static const ProtobufCEnumValueIndex failure_type__enum_values_by_name[12] =
{
  { "Failure_ActionCancelled", 3 },
  { "Failure_ButtonExpected", 1 },
  { "Failure_FirmwareError", 11 },
  { "Failure_InvalidSignature", 7 },
  { "Failure_NotEnoughFunds", 9 },
  { "Failure_NotInitialized", 10 },
  { "Failure_Other", 8 },
  { "Failure_PinCancelled", 5 },
  { "Failure_PinExpected", 4 },
  { "Failure_PinInvalid", 6 },
  { "Failure_SyntaxError", 2 },
  { "Failure_UnexpectedMessage", 0 },
};
const ProtobufCEnumDescriptor failure_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "FailureType",
  "FailureType",
  "FailureType",
  "",
  12,
  failure_type__enum_values_by_number,
  12,
  failure_type__enum_values_by_name,
  2,
  failure_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue output_script_type__enum_values_by_number[4] =
{
  { "PAYTOADDRESS", "OUTPUT_SCRIPT_TYPE__PAYTOADDRESS", 0 },
  { "PAYTOSCRIPTHASH", "OUTPUT_SCRIPT_TYPE__PAYTOSCRIPTHASH", 1 },
  { "PAYTOMULTISIG", "OUTPUT_SCRIPT_TYPE__PAYTOMULTISIG", 2 },
  { "PAYTOOPRETURN", "OUTPUT_SCRIPT_TYPE__PAYTOOPRETURN", 3 },
};
static const ProtobufCIntRange output_script_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex output_script_type__enum_values_by_name[4] =
{
  { "PAYTOADDRESS", 0 },
  { "PAYTOMULTISIG", 2 },
  { "PAYTOOPRETURN", 3 },
  { "PAYTOSCRIPTHASH", 1 },
};
const ProtobufCEnumDescriptor output_script_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "OutputScriptType",
  "OutputScriptType",
  "OutputScriptType",
  "",
  4,
  output_script_type__enum_values_by_number,
  4,
  output_script_type__enum_values_by_name,
  1,
  output_script_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue input_script_type__enum_values_by_number[2] =
{
  { "SPENDADDRESS", "INPUT_SCRIPT_TYPE__SPENDADDRESS", 0 },
  { "SPENDMULTISIG", "INPUT_SCRIPT_TYPE__SPENDMULTISIG", 1 },
};
static const ProtobufCIntRange input_script_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex input_script_type__enum_values_by_name[2] =
{
  { "SPENDADDRESS", 0 },
  { "SPENDMULTISIG", 1 },
};
const ProtobufCEnumDescriptor input_script_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "InputScriptType",
  "InputScriptType",
  "InputScriptType",
  "",
  2,
  input_script_type__enum_values_by_number,
  2,
  input_script_type__enum_values_by_name,
  1,
  input_script_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue request_type__enum_values_by_number[4] =
{
  { "TXINPUT", "REQUEST_TYPE__TXINPUT", 0 },
  { "TXOUTPUT", "REQUEST_TYPE__TXOUTPUT", 1 },
  { "TXMETA", "REQUEST_TYPE__TXMETA", 2 },
  { "TXFINISHED", "REQUEST_TYPE__TXFINISHED", 3 },
};
static const ProtobufCIntRange request_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex request_type__enum_values_by_name[4] =
{
  { "TXFINISHED", 3 },
  { "TXINPUT", 0 },
  { "TXMETA", 2 },
  { "TXOUTPUT", 1 },
};
const ProtobufCEnumDescriptor request_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "RequestType",
  "RequestType",
  "RequestType",
  "",
  4,
  request_type__enum_values_by_number,
  4,
  request_type__enum_values_by_name,
  1,
  request_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue button_request_type__enum_values_by_number[11] =
{
  { "ButtonRequest_Other", "BUTTON_REQUEST_TYPE__ButtonRequest_Other", 1 },
  { "ButtonRequest_FeeOverThreshold", "BUTTON_REQUEST_TYPE__ButtonRequest_FeeOverThreshold", 2 },
  { "ButtonRequest_ConfirmOutput", "BUTTON_REQUEST_TYPE__ButtonRequest_ConfirmOutput", 3 },
  { "ButtonRequest_ResetDevice", "BUTTON_REQUEST_TYPE__ButtonRequest_ResetDevice", 4 },
  { "ButtonRequest_ConfirmWord", "BUTTON_REQUEST_TYPE__ButtonRequest_ConfirmWord", 5 },
  { "ButtonRequest_WipeDevice", "BUTTON_REQUEST_TYPE__ButtonRequest_WipeDevice", 6 },
  { "ButtonRequest_ProtectCall", "BUTTON_REQUEST_TYPE__ButtonRequest_ProtectCall", 7 },
  { "ButtonRequest_SignTx", "BUTTON_REQUEST_TYPE__ButtonRequest_SignTx", 8 },
  { "ButtonRequest_FirmwareCheck", "BUTTON_REQUEST_TYPE__ButtonRequest_FirmwareCheck", 9 },
  { "ButtonRequest_Address", "BUTTON_REQUEST_TYPE__ButtonRequest_Address", 10 },
  { "ButtonRequest_PublicKey", "BUTTON_REQUEST_TYPE__ButtonRequest_PublicKey", 11 },
};
static const ProtobufCIntRange button_request_type__value_ranges[] = {
{1, 0},{0, 11}
};
static const ProtobufCEnumValueIndex button_request_type__enum_values_by_name[11] =
{
  { "ButtonRequest_Address", 9 },
  { "ButtonRequest_ConfirmOutput", 2 },
  { "ButtonRequest_ConfirmWord", 4 },
  { "ButtonRequest_FeeOverThreshold", 1 },
  { "ButtonRequest_FirmwareCheck", 8 },
  { "ButtonRequest_Other", 0 },
  { "ButtonRequest_ProtectCall", 6 },
  { "ButtonRequest_PublicKey", 10 },
  { "ButtonRequest_ResetDevice", 3 },
  { "ButtonRequest_SignTx", 7 },
  { "ButtonRequest_WipeDevice", 5 },
};
const ProtobufCEnumDescriptor button_request_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ButtonRequestType",
  "ButtonRequestType",
  "ButtonRequestType",
  "",
  11,
  button_request_type__enum_values_by_number,
  11,
  button_request_type__enum_values_by_name,
  1,
  button_request_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue pin_matrix_request_type__enum_values_by_number[3] =
{
  { "PinMatrixRequestType_Current", "PIN_MATRIX_REQUEST_TYPE__PinMatrixRequestType_Current", 1 },
  { "PinMatrixRequestType_NewFirst", "PIN_MATRIX_REQUEST_TYPE__PinMatrixRequestType_NewFirst", 2 },
  { "PinMatrixRequestType_NewSecond", "PIN_MATRIX_REQUEST_TYPE__PinMatrixRequestType_NewSecond", 3 },
};
static const ProtobufCIntRange pin_matrix_request_type__value_ranges[] = {
{1, 0},{0, 3}
};
static const ProtobufCEnumValueIndex pin_matrix_request_type__enum_values_by_name[3] =
{
  { "PinMatrixRequestType_Current", 0 },
  { "PinMatrixRequestType_NewFirst", 1 },
  { "PinMatrixRequestType_NewSecond", 2 },
};
const ProtobufCEnumDescriptor pin_matrix_request_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "PinMatrixRequestType",
  "PinMatrixRequestType",
  "PinMatrixRequestType",
  "",
  3,
  pin_matrix_request_type__enum_values_by_number,
  3,
  pin_matrix_request_type__enum_values_by_name,
  1,
  pin_matrix_request_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
